Repository raphael-attias/DNS-Drink-Name-Spinner, pull requests merged in 2025-04, with the labels that each got.

#11 feature spin
  index.html
Labels: enhancement

#13 Feat/micro features
  assets/css/style.css
  assets/img/metatag_bg.png
  index.html
Labels: enhancement

#15 Feat style(css)
  assets/script/script.js
  index.html
Labels: enhancement

#16 Restructuring the head
  index.html
Labels: enhancement

#18 Switch arrow on top
  assets/css/style.css
Labels: refactor

#19 Change the color of the sectors
  assets/script/script.js
Labels: enhancement

#22 fix: logo in an address bar, logo and metatag
  index.html
Labels: refactor

#29 hotfix: changing instructions
  index.html
Labels: refactor

#32 hotfix: replace the div with a button for keyboard navigation
  assets/css/style.css
  index.html
Labels: fix
